name: Isolate CMS directory for heroku
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Move cms directory to heroku-deploy branch
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: heroku-deploy
        FOLDER: cms
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
